defaults: &defaults
  doorkeeper:
    subdomain: yokohamarb
  zapier:
    twitter: "http://localhost:3000/twitter"
    google_group: "http://localhost:3000/google_group"
    facebook_group: "http://localhost:3000/facebook_group"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  doorkeeper:
    subdomain: <%= ENV["DOORKEEPER_SUBDOMAIN"] %>
  zapier:
    twitter: <%= ENV["ZAPIER_TWITTER"] %>
    google_group: <%= ENV["ZAPIER_GOOGLE_GROUP"] %>
    facebook_group: <%= ENV["ZAPIER_FACEBOOK_GROUP"] %>
