defaults: &defaults
  zapier:
    google_group: ""
    twitter: ""
    facebook_group: ""

development:
  <<: *defaults

test:
  <<: *defaults

production:
  zapier:
    google_group: <%= ENV["ZAPIER_GOOGLE_GROUP"] %>
    twitter: <%= ENV["ZAPIER_TWITTER"] %>
    facebook_group: <%= ENV["ZAPIER_FACEBOOK_GROUP"] %>
