defaults: &defaults
  zapier:
    mail: ""
    twitter: ""
    facebook: ""

development:
  <<: *defaults

test:
  <<: *defaults

production:
  zapier:
    mail: <%= ENV["ZAPIER_MAIL"] %>
    twitter: <%= ENV["ZAPIER_TWITTER"] %>
    facebook: <%= ENV["ZAPIER_FACEBOOK"] %>
